name: flutter_alice
description: Alice is an HTTP Inspector tool which helps debugging http requests. It catches and stores http requests and responses, which can be viewed via simple UI.
version: 1.1.1
homepage: https://github.com/IlhomSh/flutter_alice.git

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  dio: ^5.7.0
  chopper: ^8.0.3
  overlay_support: ^2.1.0
  share_plus: ^10.1.1
  rxdart: ^0.28.0